name: ReneeBowen
favicon: null
layout_spectrum: 0.12142389197833836
typography_spectrum: 0.6995736993849277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2710245510097593
  lightness: 0.3855042669456452
  saturation: 0.2813793560490012
  rhythmicContrast: 0.619325487408787
purpose: []
