name: ReneeBowen
favicon: null
layout_spectrum: 0.69928
typography_spectrum: 0.04585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232928'
    - '#abbab6'
    - '#ad7b68'
    - '#bc9586'
    - '#634d3f'
  brandStrength: 0.5
  lightness: 0.3855042669456452
  saturation: 0.2813793560490012
  rhythmicContrast: 0.619325487408787
purpose: []
